// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/tfsdk"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/netascode/go-restconf"
)

// Ensure the implementation satisfies the expected interfaces.
var (
	_ datasource.DataSource              = &EVPNInstanceDataSource{}
	_ datasource.DataSourceWithConfigure = &EVPNInstanceDataSource{}
)

func NewEVPNInstanceDataSource() datasource.DataSource {
	return &EVPNInstanceDataSource{}
}

type EVPNInstanceDataSource struct {
	clients map[string]*restconf.Client
}

func (d *EVPNInstanceDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_evpn_instance"
}

func (d *EVPNInstanceDataSource) GetSchema(ctx context.Context) (tfsdk.Schema, diag.Diagnostics) {
	return tfsdk.Schema{
		// This description is used by the documentation generator and the language server.
		MarkdownDescription: "This data source can read the EVPN Instance configuration.",

		Attributes: map[string]tfsdk.Attribute{
			"device": {
				MarkdownDescription: "A device name from the provider configuration.",
				Type:                types.StringType,
				Optional:            true,
			},
			"id": {
				MarkdownDescription: "The path of the retrieved object.",
				Type:                types.StringType,
				Computed:            true,
			},
			"evpn_instance_num": {
				MarkdownDescription: "evpn instance number",
				Type:                types.Int64Type,
				Required:            true,
			},
			"vlan_based_replication_type_ingress": {
				MarkdownDescription: "Ingress replication",
				Type:                types.BoolType,
				Computed:            true,
			},
			"vlan_based_replication_type_static": {
				MarkdownDescription: "Static replication",
				Type:                types.BoolType,
				Computed:            true,
			},
			"vlan_based_replication_type_p2mp": {
				MarkdownDescription: "p2mp replication",
				Type:                types.BoolType,
				Computed:            true,
			},
			"vlan_based_replication_type_mp2mp": {
				MarkdownDescription: "mp2mp replication",
				Type:                types.BoolType,
				Computed:            true,
			},
			"vlan_based_encapsulation": {
				MarkdownDescription: "Data encapsulation method",
				Type:                types.StringType,
				Computed:            true,
			},
			"vlan_based_auto_route_target": {
				MarkdownDescription: "Automatically set a route-target",
				Type:                types.BoolType,
				Computed:            true,
			},
			"vlan_based_rd": {
				MarkdownDescription: "ASN:nn or IP-address:nn",
				Type:                types.StringType,
				Computed:            true,
			},
			"vlan_based_route_target": {
				MarkdownDescription: "ASN:nn or IP-address:nn",
				Type:                types.StringType,
				Computed:            true,
			},
			"vlan_based_route_target_both": {
				MarkdownDescription: "ASN:nn or IP-address:nn",
				Type:                types.StringType,
				Computed:            true,
			},
			"vlan_based_route_target_import": {
				MarkdownDescription: "ASN:nn or IP-address:nn",
				Type:                types.StringType,
				Computed:            true,
			},
			"vlan_based_route_target_export": {
				MarkdownDescription: "ASN:nn or IP-address:nn",
				Type:                types.StringType,
				Computed:            true,
			},
			"vlan_based_ip_local_learning_disable": {
				MarkdownDescription: "Disable IP local learning from dataplane",
				Type:                types.BoolType,
				Computed:            true,
			},
			"vlan_based_ip_local_learning_enable": {
				MarkdownDescription: "Enable IP local learning from dataplane",
				Type:                types.BoolType,
				Computed:            true,
			},
			"vlan_based_default_gateway_advertise": {
				MarkdownDescription: "Advertise Default Gateway MAC/IP routes",
				Type:                types.StringType,
				Computed:            true,
			},
			"vlan_based_re_originate_route_type5": {
				MarkdownDescription: "Re-originate route-type 5",
				Type:                types.BoolType,
				Computed:            true,
			},
		},
	}, nil
}

func (d *EVPNInstanceDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, _ *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	d.clients = req.ProviderData.(map[string]*restconf.Client)
}

func (d *EVPNInstanceDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config EVPNInstance

	// Read config
	diags := req.Config.Get(ctx, &config)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	tflog.Debug(ctx, fmt.Sprintf("%s: Beginning Read", config.getPath()))

	res, err := d.clients[config.Device.ValueString()].GetData(config.getPath())
	if res.StatusCode == 404 {
		config = EVPNInstance{Device: config.Device}
	} else {
		if err != nil {
			resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Failed to retrieve object, got error: %s", err))
			return
		}

		config.fromBody(ctx, res.Res)
	}

	config.Id = types.StringValue(config.getPath())

	tflog.Debug(ctx, fmt.Sprintf("%s: Read finished successfully", config.getPath()))

	diags = resp.State.Set(ctx, &config)
	resp.Diagnostics.Append(diags...)
}
