// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestAccDataSourceIosxeStaticRoute(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccDataSourceIosxeStaticRouteConfig,
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr("data.iosxe_static_route.test", "next_hops.0.next_hop", "6.6.6.6"),
					resource.TestCheckResourceAttr("data.iosxe_static_route.test", "next_hops.0.metric", "10"),
					resource.TestCheckResourceAttr("data.iosxe_static_route.test", "next_hops.0.global", "false"),
					resource.TestCheckResourceAttr("data.iosxe_static_route.test", "next_hops.0.name", "Route1"),
					resource.TestCheckResourceAttr("data.iosxe_static_route.test", "next_hops.0.permanent", "true"),
					resource.TestCheckResourceAttr("data.iosxe_static_route.test", "next_hops.0.tag", "100"),
				),
			},
		},
	})
}

const testAccDataSourceIosxeStaticRouteConfig = `

resource "iosxe_static_route" "test" {
  prefix = "5.5.5.5"
  mask = "255.255.255.255"
  next_hops = [{
    next_hop = "6.6.6.6"
    metric = 10
    global = false
    name = "Route1"
    permanent = true
    tag = 100
  }]
}

data "iosxe_static_route" "test" {
  prefix = "5.5.5.5"
  mask = "255.255.255.255"
  depends_on = [iosxe_static_route.test]
}
`
