// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/tfsdk"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/netascode/go-restconf"
)

// Ensure the implementation satisfies the expected interfaces.
var (
	_ datasource.DataSource              = &InterfacePortChannelSubinterfaceDataSource{}
	_ datasource.DataSourceWithConfigure = &InterfacePortChannelSubinterfaceDataSource{}
)

func NewInterfacePortChannelSubinterfaceDataSource() datasource.DataSource {
	return &InterfacePortChannelSubinterfaceDataSource{}
}

type InterfacePortChannelSubinterfaceDataSource struct {
	clients map[string]*restconf.Client
}

func (d *InterfacePortChannelSubinterfaceDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_interface_port_channel_subinterface"
}

func (d *InterfacePortChannelSubinterfaceDataSource) GetSchema(ctx context.Context) (tfsdk.Schema, diag.Diagnostics) {
	return tfsdk.Schema{
		// This description is used by the documentation generator and the language server.
		MarkdownDescription: "This data source can read the Interface Port Channel Subinterface configuration.",

		Attributes: map[string]tfsdk.Attribute{
			"device": {
				MarkdownDescription: "A device name from the provider configuration.",
				Type:                types.StringType,
				Optional:            true,
			},
			"id": {
				MarkdownDescription: "The path of the retrieved object.",
				Type:                types.StringType,
				Computed:            true,
			},
			"name": {
				MarkdownDescription: "",
				Type:                types.StringType,
				Required:            true,
			},
			"description": {
				MarkdownDescription: "Interface specific description",
				Type:                types.StringType,
				Computed:            true,
			},
			"shutdown": {
				MarkdownDescription: "Shutdown the selected interface",
				Type:                types.BoolType,
				Computed:            true,
			},
			"vrf_forwarding": {
				MarkdownDescription: "Configure forwarding table",
				Type:                types.StringType,
				Computed:            true,
			},
			"ipv4_address": {
				MarkdownDescription: "",
				Type:                types.StringType,
				Computed:            true,
			},
			"ipv4_address_mask": {
				MarkdownDescription: "",
				Type:                types.StringType,
				Computed:            true,
			},
			"encapsulation_dot1q_vlan_id": {
				MarkdownDescription: "",
				Type:                types.Int64Type,
				Computed:            true,
			},
			"ip_access_group_in": {
				MarkdownDescription: "",
				Type:                types.StringType,
				Computed:            true,
			},
			"ip_access_group_in_enable": {
				MarkdownDescription: "inbound packets",
				Type:                types.BoolType,
				Computed:            true,
			},
			"ip_access_group_out": {
				MarkdownDescription: "",
				Type:                types.StringType,
				Computed:            true,
			},
			"ip_access_group_out_enable": {
				MarkdownDescription: "outbound packets",
				Type:                types.BoolType,
				Computed:            true,
			},
			"helper_addresses": {
				MarkdownDescription: "Specify a destination address for UDP broadcasts",
				Computed:            true,
				Attributes: tfsdk.ListNestedAttributes(map[string]tfsdk.Attribute{
					"address": {
						MarkdownDescription: "",
						Type:                types.StringType,
						Computed:            true,
					},
					"global": {
						MarkdownDescription: "Helper-address is global",
						Type:                types.BoolType,
						Computed:            true,
					},
					"vrf": {
						MarkdownDescription: "VRF name for helper-address (if different from interface VRF)",
						Type:                types.StringType,
						Computed:            true,
					},
				}),
			},
		},
	}, nil
}

func (d *InterfacePortChannelSubinterfaceDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, _ *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	d.clients = req.ProviderData.(map[string]*restconf.Client)
}

func (d *InterfacePortChannelSubinterfaceDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config InterfacePortChannelSubinterface

	// Read config
	diags := req.Config.Get(ctx, &config)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	tflog.Debug(ctx, fmt.Sprintf("%s: Beginning Read", config.getPath()))

	res, err := d.clients[config.Device.ValueString()].GetData(config.getPath())
	if res.StatusCode == 404 {
		config = InterfacePortChannelSubinterface{Device: config.Device}
	} else {
		if err != nil {
			resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Failed to retrieve object, got error: %s", err))
			return
		}

		config.fromBody(ctx, res.Res)
	}

	config.Id = types.StringValue(config.getPath())

	tflog.Debug(ctx, fmt.Sprintf("%s: Read finished successfully", config.getPath()))

	diags = resp.State.Set(ctx, &config)
	resp.Diagnostics.Append(diags...)
}
