// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestAccDataSourceIosxeLoggingIPv6HostTransport(t *testing.T) {
	var checks []resource.TestCheckFunc
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_logging_ipv6_host_transport.test", "transport_udp_ports.0.port_number", "10000"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_logging_ipv6_host_transport.test", "transport_tcp_ports.0.port_number", "10001"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_logging_ipv6_host_transport.test", "transport_tls_ports.0.port_number", "10002"))
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccDataSourceIosxeLoggingIPv6HostTransportConfig(),
				Check:  resource.ComposeTestCheckFunc(checks...),
			},
		},
	})
}

func testAccDataSourceIosxeLoggingIPv6HostTransportConfig() string {
	config := `resource "iosxe_logging_ipv6_host_transport" "test" {` + "\n"
	config += `	delete_mode = "attributes"\n`
	config += `	ipv6_host = "2001::1"` + "\n"
	config += `	transport_udp_ports = [{` + "\n"
	config += `		port_number = 10000` + "\n"
	config += `	}]` + "\n"
	config += `	transport_tcp_ports = [{` + "\n"
	config += `		port_number = 10001` + "\n"
	config += `	}]` + "\n"
	config += `	transport_tls_ports = [{` + "\n"
	config += `		port_number = 10002` + "\n"
	config += `	}]` + "\n"
	config += `}` + "\n"

	config += `
		data "iosxe_logging_ipv6_host_transport" "test" {
			ipv6_host = "2001::1"
			depends_on = [iosxe_logging_ipv6_host_transport.test]
		}
	`
	return config
}
