// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
)

func TestAccDataSourceIosxeInterfaceOSPF(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccDataSourceIosxeInterfaceOSPFConfig,
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr("data.iosxe_interface_ospf.test", "cost", "10"),
					resource.TestCheckResourceAttr("data.iosxe_interface_ospf.test", "dead_interval", "30"),
					resource.TestCheckResourceAttr("data.iosxe_interface_ospf.test", "hello_interval", "5"),
					resource.TestCheckResourceAttr("data.iosxe_interface_ospf.test", "mtu_ignore", "false"),
					resource.TestCheckResourceAttr("data.iosxe_interface_ospf.test", "network_type_broadcast", "false"),
					resource.TestCheckResourceAttr("data.iosxe_interface_ospf.test", "network_type_non_broadcast", "false"),
					resource.TestCheckResourceAttr("data.iosxe_interface_ospf.test", "network_type_point_to_multipoint", "false"),
					resource.TestCheckResourceAttr("data.iosxe_interface_ospf.test", "network_type_point_to_point", "true"),
					resource.TestCheckResourceAttr("data.iosxe_interface_ospf.test", "priority", "10"),
				),
			},
		},
	})
}

const testAccDataSourceIosxeInterfaceOSPFConfig = `

resource "iosxe_interface_ospf" "test" {
  type = "GigabitEthernet"
  name = "3"
  cost = 10
  dead_interval = 30
  hello_interval = 5
  mtu_ignore = false
  network_type_broadcast = false
  network_type_non_broadcast = false
  network_type_point_to_multipoint = false
  network_type_point_to_point = true
  priority = 10
}

data "iosxe_interface_ospf" "test" {
  type = "GigabitEthernet"
  name = "3"
  depends_on = [iosxe_interface_ospf.test]
}
`
