// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestAccDataSourceIosxeVRF(t *testing.T) {
	var checks []resource.TestCheckFunc
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_vrf.test", "description", "VRF22 description"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_vrf.test", "rd", "22:22"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_vrf.test", "address_family_ipv4", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_vrf.test", "address_family_ipv6", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_vrf.test", "vpn_id", "22:22"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_vrf.test", "route_target_import.0.value", "22:22"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_vrf.test", "route_target_import.0.stitching", "false"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_vrf.test", "route_target_export.0.value", "22:22"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_vrf.test", "route_target_export.0.stitching", "false"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_vrf.test", "ipv4_route_target_import.0.value", "22:22"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_vrf.test", "ipv4_route_target_import_stitching.0.value", "22:22"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_vrf.test", "ipv4_route_target_export.0.value", "22:22"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_vrf.test", "ipv4_route_target_export_stitching.0.value", "22:22"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_vrf.test", "ipv6_route_target_import.0.value", "22:22"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_vrf.test", "ipv6_route_target_import_stitching.0.value", "22:22"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_vrf.test", "ipv6_route_target_export.0.value", "22:22"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_vrf.test", "ipv6_route_target_export_stitching.0.value", "22:22"))
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccDataSourceIosxeVRFConfig(),
				Check:  resource.ComposeTestCheckFunc(checks...),
			},
		},
	})
}

func testAccDataSourceIosxeVRFConfig() string {
	config := `resource "iosxe_vrf" "test" {` + "\n"
	config += `	delete_mode = "attributes"\n`
	config += `	name = "VRF22"` + "\n"
	config += `	description = "VRF22 description"` + "\n"
	config += `	rd = "22:22"` + "\n"
	config += `	address_family_ipv4 = true` + "\n"
	config += `	address_family_ipv6 = true` + "\n"
	config += `	vpn_id = "22:22"` + "\n"
	config += `	route_target_import = [{` + "\n"
	config += `		value = "22:22"` + "\n"
	config += `		stitching = false` + "\n"
	config += `	}]` + "\n"
	config += `	route_target_export = [{` + "\n"
	config += `		value = "22:22"` + "\n"
	config += `		stitching = false` + "\n"
	config += `	}]` + "\n"
	config += `	ipv4_route_target_import = [{` + "\n"
	config += `		value = "22:22"` + "\n"
	config += `	}]` + "\n"
	config += `	ipv4_route_target_import_stitching = [{` + "\n"
	config += `		value = "22:22"` + "\n"
	config += `	}]` + "\n"
	config += `	ipv4_route_target_export = [{` + "\n"
	config += `		value = "22:22"` + "\n"
	config += `	}]` + "\n"
	config += `	ipv4_route_target_export_stitching = [{` + "\n"
	config += `		value = "22:22"` + "\n"
	config += `	}]` + "\n"
	config += `	ipv6_route_target_import = [{` + "\n"
	config += `		value = "22:22"` + "\n"
	config += `	}]` + "\n"
	config += `	ipv6_route_target_import_stitching = [{` + "\n"
	config += `		value = "22:22"` + "\n"
	config += `	}]` + "\n"
	config += `	ipv6_route_target_export = [{` + "\n"
	config += `		value = "22:22"` + "\n"
	config += `	}]` + "\n"
	config += `	ipv6_route_target_export_stitching = [{` + "\n"
	config += `		value = "22:22"` + "\n"
	config += `	}]` + "\n"
	config += `}` + "\n"

	config += `
		data "iosxe_vrf" "test" {
			name = "VRF22"
			depends_on = [iosxe_vrf.test]
		}
	`
	return config
}
