//go:build testAll

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestAccDataSourceIosxeVLAN(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccDataSourceIosxeVLANConfig,
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr("data.iosxe_vlan.test", "name", "Vlan123"),
					resource.TestCheckResourceAttr("data.iosxe_vlan.test", "shutdown", "false"),
				),
			},
		},
	})
}

const testAccDataSourceIosxeVLANConfig = `

resource "iosxe_vlan" "test" {
	vlan_id = 123
	name = "Vlan123"
	shutdown = false
}

data "iosxe_vlan" "test" {
	vlan_id = 123
	depends_on = [iosxe_vlan.test]
}
`
