// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"fmt"
	"net/url"
	"regexp"
	"strconv"

	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/netascode/terraform-provider-iosxe/internal/provider/helpers"
	"github.com/tidwall/gjson"
	"github.com/tidwall/sjson"
)

type EVPNInstance struct {
	Device                           types.String `tfsdk:"device"`
	Id                               types.String `tfsdk:"id"`
	EvpnInstanceNum                  types.Int64  `tfsdk:"evpn_instance_num"`
	VlanBasedReplicationTypeIngress  types.Bool   `tfsdk:"vlan_based_replication_type_ingress"`
	VlanBasedReplicationTypeStatic   types.Bool   `tfsdk:"vlan_based_replication_type_static"`
	VlanBasedReplicationTypeP2mp     types.Bool   `tfsdk:"vlan_based_replication_type_p2mp"`
	VlanBasedReplicationTypeMp2mp    types.Bool   `tfsdk:"vlan_based_replication_type_mp2mp"`
	VlanBasedEncapsulation           types.String `tfsdk:"vlan_based_encapsulation"`
	VlanBasedAutoRouteTarget         types.Bool   `tfsdk:"vlan_based_auto_route_target"`
	VlanBasedRd                      types.String `tfsdk:"vlan_based_rd"`
	VlanBasedRouteTarget             types.String `tfsdk:"vlan_based_route_target"`
	VlanBasedRouteTargetBoth         types.String `tfsdk:"vlan_based_route_target_both"`
	VlanBasedRouteTargetImport       types.String `tfsdk:"vlan_based_route_target_import"`
	VlanBasedRouteTargetExport       types.String `tfsdk:"vlan_based_route_target_export"`
	VlanBasedIpLocalLearningDisable  types.Bool   `tfsdk:"vlan_based_ip_local_learning_disable"`
	VlanBasedIpLocalLearningEnable   types.Bool   `tfsdk:"vlan_based_ip_local_learning_enable"`
	VlanBasedDefaultGatewayAdvertise types.String `tfsdk:"vlan_based_default_gateway_advertise"`
	VlanBasedReOriginateRouteType5   types.Bool   `tfsdk:"vlan_based_re_originate_route_type5"`
}

func (data EVPNInstance) getPath() string {
	return fmt.Sprintf("Cisco-IOS-XE-native:native/l2vpn/Cisco-IOS-XE-l2vpn:evpn_cont/evpn-instance/evpn/instance/instance=%v", url.QueryEscape(fmt.Sprintf("%v", data.EvpnInstanceNum.Value)))
}

// if last path element has a key -> remove it
func (data EVPNInstance) getPathShort() string {
	path := data.getPath()
	re := regexp.MustCompile(`(.*)=[^\/]*$`)
	matches := re.FindStringSubmatch(path)
	if len(matches) <= 1 {
		return path
	}
	return matches[1]
}

func (data EVPNInstance) toBody() string {
	body := `{"` + helpers.LastElement(data.getPath()) + `":{}}`
	if !data.EvpnInstanceNum.Null && !data.EvpnInstanceNum.Unknown {
		body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"evpn-instance-num", strconv.FormatInt(data.EvpnInstanceNum.Value, 10))
	}
	if !data.VlanBasedReplicationTypeIngress.Null && !data.VlanBasedReplicationTypeIngress.Unknown {
		if data.VlanBasedReplicationTypeIngress.Value {
			body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"vlan-based.replication-type.ingress", map[string]string{})
		}
	}
	if !data.VlanBasedReplicationTypeStatic.Null && !data.VlanBasedReplicationTypeStatic.Unknown {
		if data.VlanBasedReplicationTypeStatic.Value {
			body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"vlan-based.replication-type.static", map[string]string{})
		}
	}
	if !data.VlanBasedReplicationTypeP2mp.Null && !data.VlanBasedReplicationTypeP2mp.Unknown {
		if data.VlanBasedReplicationTypeP2mp.Value {
			body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"vlan-based.replication-type.p2mp", map[string]string{})
		}
	}
	if !data.VlanBasedReplicationTypeMp2mp.Null && !data.VlanBasedReplicationTypeMp2mp.Unknown {
		if data.VlanBasedReplicationTypeMp2mp.Value {
			body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"vlan-based.replication-type.mp2mp", map[string]string{})
		}
	}
	if !data.VlanBasedEncapsulation.Null && !data.VlanBasedEncapsulation.Unknown {
		body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"vlan-based.encapsulation", data.VlanBasedEncapsulation.Value)
	}
	if !data.VlanBasedAutoRouteTarget.Null && !data.VlanBasedAutoRouteTarget.Unknown {
		if data.VlanBasedAutoRouteTarget.Value {
			body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"vlan-based.auto-route-target_cont.auto-route-target", map[string]string{})
		}
	}
	if !data.VlanBasedRd.Null && !data.VlanBasedRd.Unknown {
		body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"vlan-based.rd.rd-value", data.VlanBasedRd.Value)
	}
	if !data.VlanBasedRouteTarget.Null && !data.VlanBasedRouteTarget.Unknown {
		body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"vlan-based.route-target.rt-value", data.VlanBasedRouteTarget.Value)
	}
	if !data.VlanBasedRouteTargetBoth.Null && !data.VlanBasedRouteTargetBoth.Unknown {
		body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"vlan-based.route-target.both.rt-value", data.VlanBasedRouteTargetBoth.Value)
	}
	if !data.VlanBasedRouteTargetImport.Null && !data.VlanBasedRouteTargetImport.Unknown {
		body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"vlan-based.route-target.import.rt-value", data.VlanBasedRouteTargetImport.Value)
	}
	if !data.VlanBasedRouteTargetExport.Null && !data.VlanBasedRouteTargetExport.Unknown {
		body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"vlan-based.route-target.export.rt-value", data.VlanBasedRouteTargetExport.Value)
	}
	if !data.VlanBasedIpLocalLearningDisable.Null && !data.VlanBasedIpLocalLearningDisable.Unknown {
		if data.VlanBasedIpLocalLearningDisable.Value {
			body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"vlan-based.ip.local-learning.disable", map[string]string{})
		}
	}
	if !data.VlanBasedIpLocalLearningEnable.Null && !data.VlanBasedIpLocalLearningEnable.Unknown {
		if data.VlanBasedIpLocalLearningEnable.Value {
			body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"vlan-based.ip.local-learning.enable", map[string]string{})
		}
	}
	if !data.VlanBasedDefaultGatewayAdvertise.Null && !data.VlanBasedDefaultGatewayAdvertise.Unknown {
		body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"vlan-based.default-gateway.advertise", data.VlanBasedDefaultGatewayAdvertise.Value)
	}
	if !data.VlanBasedReOriginateRouteType5.Null && !data.VlanBasedReOriginateRouteType5.Unknown {
		if data.VlanBasedReOriginateRouteType5.Value {
			body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"vlan-based.re-originate.route-type5", map[string]string{})
		}
	}
	return body
}

func (data *EVPNInstance) updateFromBody(res gjson.Result) {
	prefix := helpers.LastElement(data.getPath()) + "."
	if res.Get(helpers.LastElement(data.getPath())).IsArray() {
		prefix += "0."
	}
	if value := res.Get(prefix + "evpn-instance-num"); value.Exists() {
		data.EvpnInstanceNum.Value = value.Int()
	} else {
		data.EvpnInstanceNum.Null = true
	}
	if value := res.Get(prefix + "vlan-based.replication-type.ingress"); value.Exists() {
		data.VlanBasedReplicationTypeIngress.Value = true
	} else {
		data.VlanBasedReplicationTypeIngress.Value = false
	}
	if value := res.Get(prefix + "vlan-based.replication-type.static"); value.Exists() {
		data.VlanBasedReplicationTypeStatic.Value = true
	} else {
		data.VlanBasedReplicationTypeStatic.Value = false
	}
	if value := res.Get(prefix + "vlan-based.replication-type.p2mp"); value.Exists() {
		data.VlanBasedReplicationTypeP2mp.Value = true
	} else {
		data.VlanBasedReplicationTypeP2mp.Value = false
	}
	if value := res.Get(prefix + "vlan-based.replication-type.mp2mp"); value.Exists() {
		data.VlanBasedReplicationTypeMp2mp.Value = true
	} else {
		data.VlanBasedReplicationTypeMp2mp.Value = false
	}
	if value := res.Get(prefix + "vlan-based.encapsulation"); value.Exists() {
		data.VlanBasedEncapsulation.Value = value.String()
	} else {
		data.VlanBasedEncapsulation.Null = true
	}
	if value := res.Get(prefix + "vlan-based.auto-route-target_cont.auto-route-target"); value.Exists() {
		data.VlanBasedAutoRouteTarget.Value = true
	} else {
		data.VlanBasedAutoRouteTarget.Value = false
	}
	if value := res.Get(prefix + "vlan-based.rd.rd-value"); value.Exists() {
		data.VlanBasedRd.Value = value.String()
	} else {
		data.VlanBasedRd.Null = true
	}
	if value := res.Get(prefix + "vlan-based.route-target.rt-value"); value.Exists() {
		data.VlanBasedRouteTarget.Value = value.String()
	} else {
		data.VlanBasedRouteTarget.Null = true
	}
	if value := res.Get(prefix + "vlan-based.route-target.both.rt-value"); value.Exists() {
		data.VlanBasedRouteTargetBoth.Value = value.String()
	} else {
		data.VlanBasedRouteTargetBoth.Null = true
	}
	if value := res.Get(prefix + "vlan-based.route-target.import.rt-value"); value.Exists() {
		data.VlanBasedRouteTargetImport.Value = value.String()
	} else {
		data.VlanBasedRouteTargetImport.Null = true
	}
	if value := res.Get(prefix + "vlan-based.route-target.export.rt-value"); value.Exists() {
		data.VlanBasedRouteTargetExport.Value = value.String()
	} else {
		data.VlanBasedRouteTargetExport.Null = true
	}
	if value := res.Get(prefix + "vlan-based.ip.local-learning.disable"); value.Exists() {
		data.VlanBasedIpLocalLearningDisable.Value = true
	} else {
		data.VlanBasedIpLocalLearningDisable.Value = false
	}
	if value := res.Get(prefix + "vlan-based.ip.local-learning.enable"); value.Exists() {
		data.VlanBasedIpLocalLearningEnable.Value = true
	} else {
		data.VlanBasedIpLocalLearningEnable.Value = false
	}
	if value := res.Get(prefix + "vlan-based.default-gateway.advertise"); value.Exists() {
		data.VlanBasedDefaultGatewayAdvertise.Value = value.String()
	} else {
		data.VlanBasedDefaultGatewayAdvertise.Null = true
	}
	if value := res.Get(prefix + "vlan-based.re-originate.route-type5"); value.Exists() {
		data.VlanBasedReOriginateRouteType5.Value = true
	} else {
		data.VlanBasedReOriginateRouteType5.Value = false
	}
}

func (data *EVPNInstance) fromBody(res gjson.Result) {
	prefix := helpers.LastElement(data.getPath()) + "."
	if res.Get(helpers.LastElement(data.getPath())).IsArray() {
		prefix += "0."
	}
	if value := res.Get(prefix + "vlan-based.replication-type.ingress"); value.Exists() {
		data.VlanBasedReplicationTypeIngress.Value = true
		data.VlanBasedReplicationTypeIngress.Null = false
	} else {
		data.VlanBasedReplicationTypeIngress.Value = false
		data.VlanBasedReplicationTypeIngress.Null = false
	}
	if value := res.Get(prefix + "vlan-based.replication-type.static"); value.Exists() {
		data.VlanBasedReplicationTypeStatic.Value = true
		data.VlanBasedReplicationTypeStatic.Null = false
	} else {
		data.VlanBasedReplicationTypeStatic.Value = false
		data.VlanBasedReplicationTypeStatic.Null = false
	}
	if value := res.Get(prefix + "vlan-based.replication-type.p2mp"); value.Exists() {
		data.VlanBasedReplicationTypeP2mp.Value = true
		data.VlanBasedReplicationTypeP2mp.Null = false
	} else {
		data.VlanBasedReplicationTypeP2mp.Value = false
		data.VlanBasedReplicationTypeP2mp.Null = false
	}
	if value := res.Get(prefix + "vlan-based.replication-type.mp2mp"); value.Exists() {
		data.VlanBasedReplicationTypeMp2mp.Value = true
		data.VlanBasedReplicationTypeMp2mp.Null = false
	} else {
		data.VlanBasedReplicationTypeMp2mp.Value = false
		data.VlanBasedReplicationTypeMp2mp.Null = false
	}
	if value := res.Get(prefix + "vlan-based.encapsulation"); value.Exists() {
		data.VlanBasedEncapsulation.Value = value.String()
		data.VlanBasedEncapsulation.Null = false
	}
	if value := res.Get(prefix + "vlan-based.auto-route-target_cont.auto-route-target"); value.Exists() {
		data.VlanBasedAutoRouteTarget.Value = true
		data.VlanBasedAutoRouteTarget.Null = false
	} else {
		data.VlanBasedAutoRouteTarget.Value = false
		data.VlanBasedAutoRouteTarget.Null = false
	}
	if value := res.Get(prefix + "vlan-based.rd.rd-value"); value.Exists() {
		data.VlanBasedRd.Value = value.String()
		data.VlanBasedRd.Null = false
	}
	if value := res.Get(prefix + "vlan-based.route-target.rt-value"); value.Exists() {
		data.VlanBasedRouteTarget.Value = value.String()
		data.VlanBasedRouteTarget.Null = false
	}
	if value := res.Get(prefix + "vlan-based.route-target.both.rt-value"); value.Exists() {
		data.VlanBasedRouteTargetBoth.Value = value.String()
		data.VlanBasedRouteTargetBoth.Null = false
	}
	if value := res.Get(prefix + "vlan-based.route-target.import.rt-value"); value.Exists() {
		data.VlanBasedRouteTargetImport.Value = value.String()
		data.VlanBasedRouteTargetImport.Null = false
	}
	if value := res.Get(prefix + "vlan-based.route-target.export.rt-value"); value.Exists() {
		data.VlanBasedRouteTargetExport.Value = value.String()
		data.VlanBasedRouteTargetExport.Null = false
	}
	if value := res.Get(prefix + "vlan-based.ip.local-learning.disable"); value.Exists() {
		data.VlanBasedIpLocalLearningDisable.Value = true
		data.VlanBasedIpLocalLearningDisable.Null = false
	} else {
		data.VlanBasedIpLocalLearningDisable.Value = false
		data.VlanBasedIpLocalLearningDisable.Null = false
	}
	if value := res.Get(prefix + "vlan-based.ip.local-learning.enable"); value.Exists() {
		data.VlanBasedIpLocalLearningEnable.Value = true
		data.VlanBasedIpLocalLearningEnable.Null = false
	} else {
		data.VlanBasedIpLocalLearningEnable.Value = false
		data.VlanBasedIpLocalLearningEnable.Null = false
	}
	if value := res.Get(prefix + "vlan-based.default-gateway.advertise"); value.Exists() {
		data.VlanBasedDefaultGatewayAdvertise.Value = value.String()
		data.VlanBasedDefaultGatewayAdvertise.Null = false
	}
	if value := res.Get(prefix + "vlan-based.re-originate.route-type5"); value.Exists() {
		data.VlanBasedReOriginateRouteType5.Value = true
		data.VlanBasedReOriginateRouteType5.Null = false
	} else {
		data.VlanBasedReOriginateRouteType5.Value = false
		data.VlanBasedReOriginateRouteType5.Null = false
	}
}

func (data *EVPNInstance) setUnknownValues() {
	if data.Device.Unknown {
		data.Device.Unknown = false
		data.Device.Null = true
	}
	if data.Id.Unknown {
		data.Id.Unknown = false
		data.Id.Null = true
	}
	if data.EvpnInstanceNum.Unknown {
		data.EvpnInstanceNum.Unknown = false
		data.EvpnInstanceNum.Null = true
	}
	if data.VlanBasedReplicationTypeIngress.Unknown {
		data.VlanBasedReplicationTypeIngress.Unknown = false
		data.VlanBasedReplicationTypeIngress.Null = true
	}
	if data.VlanBasedReplicationTypeStatic.Unknown {
		data.VlanBasedReplicationTypeStatic.Unknown = false
		data.VlanBasedReplicationTypeStatic.Null = true
	}
	if data.VlanBasedReplicationTypeP2mp.Unknown {
		data.VlanBasedReplicationTypeP2mp.Unknown = false
		data.VlanBasedReplicationTypeP2mp.Null = true
	}
	if data.VlanBasedReplicationTypeMp2mp.Unknown {
		data.VlanBasedReplicationTypeMp2mp.Unknown = false
		data.VlanBasedReplicationTypeMp2mp.Null = true
	}
	if data.VlanBasedEncapsulation.Unknown {
		data.VlanBasedEncapsulation.Unknown = false
		data.VlanBasedEncapsulation.Null = true
	}
	if data.VlanBasedAutoRouteTarget.Unknown {
		data.VlanBasedAutoRouteTarget.Unknown = false
		data.VlanBasedAutoRouteTarget.Null = true
	}
	if data.VlanBasedRd.Unknown {
		data.VlanBasedRd.Unknown = false
		data.VlanBasedRd.Null = true
	}
	if data.VlanBasedRouteTarget.Unknown {
		data.VlanBasedRouteTarget.Unknown = false
		data.VlanBasedRouteTarget.Null = true
	}
	if data.VlanBasedRouteTargetBoth.Unknown {
		data.VlanBasedRouteTargetBoth.Unknown = false
		data.VlanBasedRouteTargetBoth.Null = true
	}
	if data.VlanBasedRouteTargetImport.Unknown {
		data.VlanBasedRouteTargetImport.Unknown = false
		data.VlanBasedRouteTargetImport.Null = true
	}
	if data.VlanBasedRouteTargetExport.Unknown {
		data.VlanBasedRouteTargetExport.Unknown = false
		data.VlanBasedRouteTargetExport.Null = true
	}
	if data.VlanBasedIpLocalLearningDisable.Unknown {
		data.VlanBasedIpLocalLearningDisable.Unknown = false
		data.VlanBasedIpLocalLearningDisable.Null = true
	}
	if data.VlanBasedIpLocalLearningEnable.Unknown {
		data.VlanBasedIpLocalLearningEnable.Unknown = false
		data.VlanBasedIpLocalLearningEnable.Null = true
	}
	if data.VlanBasedDefaultGatewayAdvertise.Unknown {
		data.VlanBasedDefaultGatewayAdvertise.Unknown = false
		data.VlanBasedDefaultGatewayAdvertise.Null = true
	}
	if data.VlanBasedReOriginateRouteType5.Unknown {
		data.VlanBasedReOriginateRouteType5.Unknown = false
		data.VlanBasedReOriginateRouteType5.Null = true
	}
}

func (data *EVPNInstance) getDeletedListItems(state EVPNInstance) []string {
	deletedListItems := make([]string, 0)
	return deletedListItems
}
