// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"context"
	"regexp"

	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/netascode/terraform-provider-iosxe/internal/provider/helpers"
	"github.com/tidwall/gjson"
	"github.com/tidwall/sjson"
)

type Banner struct {
	Device              types.String `tfsdk:"device"`
	Id                  types.String `tfsdk:"id"`
	ExecBanner          types.String `tfsdk:"exec_banner"`
	LoginBanner         types.String `tfsdk:"login_banner"`
	PromptTimeoutBanner types.String `tfsdk:"prompt_timeout_banner"`
	MotdBanner          types.String `tfsdk:"motd_banner"`
}

func (data Banner) getPath() string {
	return "Cisco-IOS-XE-native:native/banner"
}

// if last path element has a key -> remove it
func (data Banner) getPathShort() string {
	path := data.getPath()
	re := regexp.MustCompile(`(.*)=[^\/]*$`)
	matches := re.FindStringSubmatch(path)
	if len(matches) <= 1 {
		return path
	}
	return matches[1]
}

func (data Banner) toBody(ctx context.Context) string {
	body := `{"` + helpers.LastElement(data.getPath()) + `":{}}`
	if !data.ExecBanner.IsNull() && !data.ExecBanner.IsUnknown() {
		body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"exec.banner", data.ExecBanner.ValueString())
	}
	if !data.LoginBanner.IsNull() && !data.LoginBanner.IsUnknown() {
		body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"login.banner", data.LoginBanner.ValueString())
	}
	if !data.PromptTimeoutBanner.IsNull() && !data.PromptTimeoutBanner.IsUnknown() {
		body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"prompt-timeout.banner", data.PromptTimeoutBanner.ValueString())
	}
	if !data.MotdBanner.IsNull() && !data.MotdBanner.IsUnknown() {
		body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"motd.banner", data.MotdBanner.ValueString())
	}
	return body
}

func (data *Banner) updateFromBody(ctx context.Context, res gjson.Result) {
	prefix := helpers.LastElement(data.getPath()) + "."
	if res.Get(helpers.LastElement(data.getPath())).IsArray() {
		prefix += "0."
	}
	if value := res.Get(prefix + "exec.banner"); value.Exists() {
		data.ExecBanner = types.StringValue(value.String())
	} else {
		data.ExecBanner = types.StringNull()
	}
	if value := res.Get(prefix + "login.banner"); value.Exists() {
		data.LoginBanner = types.StringValue(value.String())
	} else {
		data.LoginBanner = types.StringNull()
	}
	if value := res.Get(prefix + "prompt-timeout.banner"); value.Exists() {
		data.PromptTimeoutBanner = types.StringValue(value.String())
	} else {
		data.PromptTimeoutBanner = types.StringNull()
	}
	if value := res.Get(prefix + "motd.banner"); value.Exists() {
		data.MotdBanner = types.StringValue(value.String())
	} else {
		data.MotdBanner = types.StringNull()
	}
}

func (data *Banner) fromBody(ctx context.Context, res gjson.Result) {
	prefix := helpers.LastElement(data.getPath()) + "."
	if res.Get(helpers.LastElement(data.getPath())).IsArray() {
		prefix += "0."
	}
	if value := res.Get(prefix + "exec.banner"); value.Exists() {
		data.ExecBanner = types.StringValue(value.String())
	}
	if value := res.Get(prefix + "login.banner"); value.Exists() {
		data.LoginBanner = types.StringValue(value.String())
	}
	if value := res.Get(prefix + "prompt-timeout.banner"); value.Exists() {
		data.PromptTimeoutBanner = types.StringValue(value.String())
	}
	if value := res.Get(prefix + "motd.banner"); value.Exists() {
		data.MotdBanner = types.StringValue(value.String())
	}
}

func (data *Banner) setUnknownValues(ctx context.Context) {
	if data.Device.IsUnknown() {
		data.Device = types.StringNull()
	}
	if data.Id.IsUnknown() {
		data.Id = types.StringNull()
	}
	if data.ExecBanner.IsUnknown() {
		data.ExecBanner = types.StringNull()
	}
	if data.LoginBanner.IsUnknown() {
		data.LoginBanner = types.StringNull()
	}
	if data.PromptTimeoutBanner.IsUnknown() {
		data.PromptTimeoutBanner = types.StringNull()
	}
	if data.MotdBanner.IsUnknown() {
		data.MotdBanner = types.StringNull()
	}
}

func (data *Banner) getDeletedListItems(ctx context.Context, state Banner) []string {
	deletedListItems := make([]string, 0)
	return deletedListItems
}

func (data *Banner) getEmptyLeafsDelete(ctx context.Context) []string {
	emptyLeafsDelete := make([]string, 0)
	return emptyLeafsDelete
}
