// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"net/url"
	"reflect"
	"regexp"
	"strconv"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/netascode/terraform-provider-iosxe/internal/provider/helpers"
	"github.com/tidwall/gjson"
	"github.com/tidwall/sjson"
)

type InterfaceOSPFProcess struct {
	Device    types.String               `tfsdk:"device"`
	Id        types.String               `tfsdk:"id"`
	Type      types.String               `tfsdk:"type"`
	Name      types.String               `tfsdk:"name"`
	ProcessId types.Int64                `tfsdk:"process_id"`
	Area      []InterfaceOSPFProcessArea `tfsdk:"area"`
}
type InterfaceOSPFProcessArea struct {
	AreaId types.String `tfsdk:"area_id"`
}

func (data InterfaceOSPFProcess) getPath() string {
	return fmt.Sprintf("Cisco-IOS-XE-native:native/interface/%s=%v/ip/Cisco-IOS-XE-ospf:router-ospf/ospf/process-id=%v", url.QueryEscape(fmt.Sprintf("%v", data.Type.Value)), url.QueryEscape(fmt.Sprintf("%v", data.Name.Value)), url.QueryEscape(fmt.Sprintf("%v", data.ProcessId.Value)))
}

// if last path element has a key -> remove it
func (data InterfaceOSPFProcess) getPathShort() string {
	path := data.getPath()
	re := regexp.MustCompile(`(.*)=[^\/]*$`)
	matches := re.FindStringSubmatch(path)
	if len(matches) <= 1 {
		return path
	}
	return matches[1]
}

func (data InterfaceOSPFProcess) toBody(ctx context.Context) string {
	body := `{"` + helpers.LastElement(data.getPath()) + `":{}}`
	if !data.ProcessId.Null && !data.ProcessId.Unknown {
		body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"id", strconv.FormatInt(data.ProcessId.Value, 10))
	}
	if len(data.Area) > 0 {
		body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"area", []interface{}{})
		for index, item := range data.Area {
			if !item.AreaId.Null && !item.AreaId.Unknown {
				body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"area"+"."+strconv.Itoa(index)+"."+"area-id", item.AreaId.Value)
			}
		}
	}
	return body
}

func (data *InterfaceOSPFProcess) updateFromBody(ctx context.Context, res gjson.Result) {
	prefix := helpers.LastElement(data.getPath()) + "."
	if res.Get(helpers.LastElement(data.getPath())).IsArray() {
		prefix += "0."
	}
	if value := res.Get(prefix + "id"); value.Exists() {
		data.ProcessId.Value = value.Int()
	} else {
		data.ProcessId.Null = true
	}
	for i := range data.Area {
		keys := [...]string{"area-id"}
		keyValues := [...]string{data.Area[i].AreaId.Value}

		var r gjson.Result
		res.Get(prefix + "area").ForEach(
			func(_, v gjson.Result) bool {
				found := false
				for ik := range keys {
					if v.Get(keys[ik]).String() == keyValues[ik] {
						found = true
						continue
					}
					found = false
					break
				}
				if found {
					r = v
					return false
				}
				return true
			},
		)
		if value := r.Get("area-id"); value.Exists() {
			data.Area[i].AreaId.Value = value.String()
		} else {
			data.Area[i].AreaId.Null = true
		}
	}
}

func (data *InterfaceOSPFProcess) fromBody(ctx context.Context, res gjson.Result) {
	prefix := helpers.LastElement(data.getPath()) + "."
	if res.Get(helpers.LastElement(data.getPath())).IsArray() {
		prefix += "0."
	}
	if value := res.Get(prefix + "area"); value.Exists() {
		data.Area = make([]InterfaceOSPFProcessArea, 0)
		value.ForEach(func(k, v gjson.Result) bool {
			item := InterfaceOSPFProcessArea{}
			if cValue := v.Get("area-id"); cValue.Exists() {
				item.AreaId.Value = cValue.String()
				item.AreaId.Null = false
			}
			data.Area = append(data.Area, item)
			return true
		})
	}
}

func (data *InterfaceOSPFProcess) setUnknownValues(ctx context.Context) {
	if data.Device.Unknown {
		data.Device.Unknown = false
		data.Device.Null = true
	}
	if data.Id.Unknown {
		data.Id.Unknown = false
		data.Id.Null = true
	}
	if data.Type.Unknown {
		data.Type.Unknown = false
		data.Type.Null = true
	}
	if data.Name.Unknown {
		data.Name.Unknown = false
		data.Name.Null = true
	}
	if data.ProcessId.Unknown {
		data.ProcessId.Unknown = false
		data.ProcessId.Null = true
	}
	for i := range data.Area {
		if data.Area[i].AreaId.Unknown {
			data.Area[i].AreaId.Unknown = false
			data.Area[i].AreaId.Null = true
		}
	}
}

func (data *InterfaceOSPFProcess) getDeletedListItems(ctx context.Context, state InterfaceOSPFProcess) []string {
	deletedListItems := make([]string, 0)
	for i := range state.Area {
		stateKeyValues := [...]string{state.Area[i].AreaId.Value}

		emptyKeys := true
		if !reflect.ValueOf(state.Area[i].AreaId.Value).IsZero() {
			emptyKeys = false
		}
		if emptyKeys {
			continue
		}

		found := false
		for j := range data.Area {
			found = true
			if state.Area[i].AreaId.Value != data.Area[j].AreaId.Value {
				found = false
			}
			if found {
				break
			}
		}
		if !found {
			deletedListItems = append(deletedListItems, fmt.Sprintf("%v/area=%v", state.getPath(), strings.Join(stateKeyValues[:], ",")))
		}
	}
	return deletedListItems
}

func (data *InterfaceOSPFProcess) getEmptyLeafsDelete(ctx context.Context) []string {
	emptyLeafsDelete := make([]string, 0)

	return emptyLeafsDelete
}
