// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"reflect"
	"regexp"
	"strconv"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/netascode/terraform-provider-iosxe/internal/provider/helpers"
	"github.com/tidwall/gjson"
	"github.com/tidwall/sjson"
)

type System struct {
	Device                      types.String                 `tfsdk:"device"`
	Id                          types.String                 `tfsdk:"id"`
	Hostname                    types.String                 `tfsdk:"hostname"`
	IpRouting                   types.Bool                   `tfsdk:"ip_routing"`
	Ipv6UnicastRouting          types.Bool                   `tfsdk:"ipv6_unicast_routing"`
	Mtu                         types.Int64                  `tfsdk:"mtu"`
	IpSourceRoute               types.Bool                   `tfsdk:"ip_source_route"`
	IpDomainLookup              types.Bool                   `tfsdk:"ip_domain_lookup"`
	IpDomainName                types.String                 `tfsdk:"ip_domain_name"`
	LoginDelay                  types.Int64                  `tfsdk:"login_delay"`
	LoginOnFailure              types.Bool                   `tfsdk:"login_on_failure"`
	LoginOnFailureLog           types.Bool                   `tfsdk:"login_on_failure_log"`
	LoginOnSuccess              types.Bool                   `tfsdk:"login_on_success"`
	LoginOnSuccessLog           types.Bool                   `tfsdk:"login_on_success_log"`
	MulticastRouting            types.Bool                   `tfsdk:"multicast_routing"`
	MulticastRoutingSwitch      types.Bool                   `tfsdk:"multicast_routing_switch"`
	MulticastRoutingDistributed types.Bool                   `tfsdk:"multicast_routing_distributed"`
	MulticastRoutingVrfs        []SystemMulticastRoutingVrfs `tfsdk:"multicast_routing_vrfs"`
}
type SystemMulticastRoutingVrfs struct {
	Vrf         types.String `tfsdk:"vrf"`
	Distributed types.Bool   `tfsdk:"distributed"`
}

func (data System) getPath() string {
	return "Cisco-IOS-XE-native:native"
}

// if last path element has a key -> remove it
func (data System) getPathShort() string {
	path := data.getPath()
	re := regexp.MustCompile(`(.*)=[^\/]*$`)
	matches := re.FindStringSubmatch(path)
	if len(matches) <= 1 {
		return path
	}
	return matches[1]
}

func (data System) toBody(ctx context.Context) string {
	body := `{"` + helpers.LastElement(data.getPath()) + `":{}}`
	if !data.Hostname.Null && !data.Hostname.Unknown {
		body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"hostname", data.Hostname.Value)
	}
	if !data.IpRouting.Null && !data.IpRouting.Unknown {
		body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"ip.routing-conf.routing", data.IpRouting.Value)
	}
	if !data.Ipv6UnicastRouting.Null && !data.Ipv6UnicastRouting.Unknown {
		if data.Ipv6UnicastRouting.Value {
			body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"ipv6.unicast-routing", map[string]string{})
		}
	}
	if !data.Mtu.Null && !data.Mtu.Unknown {
		body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"system.Cisco-IOS-XE-switch:mtu.size", strconv.FormatInt(data.Mtu.Value, 10))
	}
	if !data.IpSourceRoute.Null && !data.IpSourceRoute.Unknown {
		body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"ip.source-route", data.IpSourceRoute.Value)
	}
	if !data.IpDomainLookup.Null && !data.IpDomainLookup.Unknown {
		body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"ip.domain.lookup", data.IpDomainLookup.Value)
	}
	if !data.IpDomainName.Null && !data.IpDomainName.Unknown {
		body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"ip.domain.name", data.IpDomainName.Value)
	}
	if !data.LoginDelay.Null && !data.LoginDelay.Unknown {
		body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"login.delay", strconv.FormatInt(data.LoginDelay.Value, 10))
	}
	if !data.LoginOnFailure.Null && !data.LoginOnFailure.Unknown {
		if data.LoginOnFailure.Value {
			body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"login.on-failure", map[string]string{})
		}
	}
	if !data.LoginOnFailureLog.Null && !data.LoginOnFailureLog.Unknown {
		if data.LoginOnFailureLog.Value {
			body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"login.on-failure.log", map[string]string{})
		}
	}
	if !data.LoginOnSuccess.Null && !data.LoginOnSuccess.Unknown {
		if data.LoginOnSuccess.Value {
			body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"login.on-success", map[string]string{})
		}
	}
	if !data.LoginOnSuccessLog.Null && !data.LoginOnSuccessLog.Unknown {
		if data.LoginOnSuccessLog.Value {
			body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"login.on-success.log", map[string]string{})
		}
	}
	if !data.MulticastRouting.Null && !data.MulticastRouting.Unknown {
		if data.MulticastRouting.Value {
			body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"ip.Cisco-IOS-XE-multicast:multicast-routing", map[string]string{})
		}
	}
	if !data.MulticastRoutingSwitch.Null && !data.MulticastRoutingSwitch.Unknown {
		if data.MulticastRoutingSwitch.Value {
			body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"ip.Cisco-IOS-XE-multicast:mcr-conf.multicast-routing", map[string]string{})
		}
	}
	if !data.MulticastRoutingDistributed.Null && !data.MulticastRoutingDistributed.Unknown {
		if data.MulticastRoutingDistributed.Value {
			body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"ip.Cisco-IOS-XE-multicast:multicast-routing.distributed", map[string]string{})
		}
	}
	if len(data.MulticastRoutingVrfs) > 0 {
		body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"ip.Cisco-IOS-XE-multicast:multicast-routing.vrf", []interface{}{})
		for index, item := range data.MulticastRoutingVrfs {
			if !item.Vrf.Null && !item.Vrf.Unknown {
				body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"ip.Cisco-IOS-XE-multicast:multicast-routing.vrf"+"."+strconv.Itoa(index)+"."+"name", item.Vrf.Value)
			}
			if !item.Distributed.Null && !item.Distributed.Unknown {
				if item.Distributed.Value {
					body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"ip.Cisco-IOS-XE-multicast:multicast-routing.vrf"+"."+strconv.Itoa(index)+"."+"distributed", map[string]string{})
				}
			}
		}
	}
	return body
}

func (data *System) updateFromBody(ctx context.Context, res gjson.Result) {
	prefix := helpers.LastElement(data.getPath()) + "."
	if res.Get(helpers.LastElement(data.getPath())).IsArray() {
		prefix += "0."
	}
	if value := res.Get(prefix + "hostname"); value.Exists() {
		data.Hostname.Value = value.String()
	} else {
		data.Hostname.Null = true
	}
	if value := res.Get(prefix + "ip.routing-conf.routing"); value.Exists() {
		data.IpRouting.Value = value.Bool()
	} else {
		data.IpRouting.Value = false
	}
	if value := res.Get(prefix + "ipv6.unicast-routing"); value.Exists() {
		data.Ipv6UnicastRouting.Value = true
	} else {
		data.Ipv6UnicastRouting.Value = false
	}
	if value := res.Get(prefix + "system.Cisco-IOS-XE-switch:mtu.size"); value.Exists() {
		data.Mtu.Value = value.Int()
	} else {
		data.Mtu.Null = true
	}
	if value := res.Get(prefix + "ip.source-route"); value.Exists() {
		data.IpSourceRoute.Value = value.Bool()
	} else {
		data.IpSourceRoute.Value = false
	}
	if value := res.Get(prefix + "ip.domain.lookup"); value.Exists() {
		data.IpDomainLookup.Value = value.Bool()
	} else {
		data.IpDomainLookup.Value = false
	}
	if value := res.Get(prefix + "ip.domain.name"); value.Exists() {
		data.IpDomainName.Value = value.String()
	} else {
		data.IpDomainName.Null = true
	}
	if value := res.Get(prefix + "login.delay"); value.Exists() {
		data.LoginDelay.Value = value.Int()
	} else {
		data.LoginDelay.Null = true
	}
	if value := res.Get(prefix + "login.on-failure"); value.Exists() {
		data.LoginOnFailure.Value = true
	} else {
		data.LoginOnFailure.Value = false
	}
	if value := res.Get(prefix + "login.on-failure.log"); value.Exists() {
		data.LoginOnFailureLog.Value = true
	} else {
		data.LoginOnFailureLog.Value = false
	}
	if value := res.Get(prefix + "login.on-success"); value.Exists() {
		data.LoginOnSuccess.Value = true
	} else {
		data.LoginOnSuccess.Value = false
	}
	if value := res.Get(prefix + "login.on-success.log"); value.Exists() {
		data.LoginOnSuccessLog.Value = true
	} else {
		data.LoginOnSuccessLog.Value = false
	}
	if value := res.Get(prefix + "ip.Cisco-IOS-XE-multicast:multicast-routing"); value.Exists() {
		data.MulticastRouting.Value = true
	} else {
		data.MulticastRouting.Value = false
	}
	if value := res.Get(prefix + "ip.Cisco-IOS-XE-multicast:mcr-conf.multicast-routing"); value.Exists() {
		data.MulticastRoutingSwitch.Value = true
	} else {
		data.MulticastRoutingSwitch.Value = false
	}
	if value := res.Get(prefix + "ip.Cisco-IOS-XE-multicast:multicast-routing.distributed"); value.Exists() {
		data.MulticastRoutingDistributed.Value = true
	} else {
		data.MulticastRoutingDistributed.Value = false
	}
	for i := range data.MulticastRoutingVrfs {
		keys := [...]string{"name"}
		keyValues := [...]string{data.MulticastRoutingVrfs[i].Vrf.Value}

		var r gjson.Result
		res.Get(prefix + "ip.Cisco-IOS-XE-multicast:multicast-routing.vrf").ForEach(
			func(_, v gjson.Result) bool {
				found := false
				for ik := range keys {
					if v.Get(keys[ik]).String() == keyValues[ik] {
						found = true
						continue
					}
					found = false
					break
				}
				if found {
					r = v
					return false
				}
				return true
			},
		)
		if value := r.Get("name"); value.Exists() {
			data.MulticastRoutingVrfs[i].Vrf.Value = value.String()
		} else {
			data.MulticastRoutingVrfs[i].Vrf.Null = true
		}
		if value := r.Get("distributed"); value.Exists() {
			data.MulticastRoutingVrfs[i].Distributed.Value = true
		} else {
			data.MulticastRoutingVrfs[i].Distributed.Value = false
		}
	}
}

func (data *System) fromBody(ctx context.Context, res gjson.Result) {
	prefix := helpers.LastElement(data.getPath()) + "."
	if res.Get(helpers.LastElement(data.getPath())).IsArray() {
		prefix += "0."
	}
	if value := res.Get(prefix + "hostname"); value.Exists() {
		data.Hostname.Value = value.String()
		data.Hostname.Null = false
	}
	if value := res.Get(prefix + "ip.routing-conf.routing"); value.Exists() {
		data.IpRouting.Value = value.Bool()
		data.IpRouting.Null = false
	} else {
		data.IpRouting.Value = false
		data.IpRouting.Null = false
	}
	if value := res.Get(prefix + "ipv6.unicast-routing"); value.Exists() {
		data.Ipv6UnicastRouting.Value = true
		data.Ipv6UnicastRouting.Null = false
	} else {
		data.Ipv6UnicastRouting.Value = false
		data.Ipv6UnicastRouting.Null = false
	}
	if value := res.Get(prefix + "system.Cisco-IOS-XE-switch:mtu.size"); value.Exists() {
		data.Mtu.Value = value.Int()
		data.Mtu.Null = false
	}
	if value := res.Get(prefix + "ip.source-route"); value.Exists() {
		data.IpSourceRoute.Value = value.Bool()
		data.IpSourceRoute.Null = false
	} else {
		data.IpSourceRoute.Value = false
		data.IpSourceRoute.Null = false
	}
	if value := res.Get(prefix + "ip.domain.lookup"); value.Exists() {
		data.IpDomainLookup.Value = value.Bool()
		data.IpDomainLookup.Null = false
	} else {
		data.IpDomainLookup.Value = false
		data.IpDomainLookup.Null = false
	}
	if value := res.Get(prefix + "ip.domain.name"); value.Exists() {
		data.IpDomainName.Value = value.String()
		data.IpDomainName.Null = false
	}
	if value := res.Get(prefix + "login.delay"); value.Exists() {
		data.LoginDelay.Value = value.Int()
		data.LoginDelay.Null = false
	}
	if value := res.Get(prefix + "login.on-failure"); value.Exists() {
		data.LoginOnFailure.Value = true
		data.LoginOnFailure.Null = false
	} else {
		data.LoginOnFailure.Value = false
		data.LoginOnFailure.Null = false
	}
	if value := res.Get(prefix + "login.on-failure.log"); value.Exists() {
		data.LoginOnFailureLog.Value = true
		data.LoginOnFailureLog.Null = false
	} else {
		data.LoginOnFailureLog.Value = false
		data.LoginOnFailureLog.Null = false
	}
	if value := res.Get(prefix + "login.on-success"); value.Exists() {
		data.LoginOnSuccess.Value = true
		data.LoginOnSuccess.Null = false
	} else {
		data.LoginOnSuccess.Value = false
		data.LoginOnSuccess.Null = false
	}
	if value := res.Get(prefix + "login.on-success.log"); value.Exists() {
		data.LoginOnSuccessLog.Value = true
		data.LoginOnSuccessLog.Null = false
	} else {
		data.LoginOnSuccessLog.Value = false
		data.LoginOnSuccessLog.Null = false
	}
	if value := res.Get(prefix + "ip.Cisco-IOS-XE-multicast:multicast-routing"); value.Exists() {
		data.MulticastRouting.Value = true
		data.MulticastRouting.Null = false
	} else {
		data.MulticastRouting.Value = false
		data.MulticastRouting.Null = false
	}
	if value := res.Get(prefix + "ip.Cisco-IOS-XE-multicast:mcr-conf.multicast-routing"); value.Exists() {
		data.MulticastRoutingSwitch.Value = true
		data.MulticastRoutingSwitch.Null = false
	} else {
		data.MulticastRoutingSwitch.Value = false
		data.MulticastRoutingSwitch.Null = false
	}
	if value := res.Get(prefix + "ip.Cisco-IOS-XE-multicast:multicast-routing.distributed"); value.Exists() {
		data.MulticastRoutingDistributed.Value = true
		data.MulticastRoutingDistributed.Null = false
	} else {
		data.MulticastRoutingDistributed.Value = false
		data.MulticastRoutingDistributed.Null = false
	}
	if value := res.Get(prefix + "ip.Cisco-IOS-XE-multicast:multicast-routing.vrf"); value.Exists() {
		data.MulticastRoutingVrfs = make([]SystemMulticastRoutingVrfs, 0)
		value.ForEach(func(k, v gjson.Result) bool {
			item := SystemMulticastRoutingVrfs{}
			if cValue := v.Get("name"); cValue.Exists() {
				item.Vrf.Value = cValue.String()
				item.Vrf.Null = false
			}
			if cValue := v.Get("distributed"); cValue.Exists() {
				item.Distributed.Value = true
				item.Distributed.Null = false
			}
			data.MulticastRoutingVrfs = append(data.MulticastRoutingVrfs, item)
			return true
		})
	}
}

func (data *System) setUnknownValues(ctx context.Context) {
	if data.Device.Unknown {
		data.Device.Unknown = false
		data.Device.Null = true
	}
	if data.Id.Unknown {
		data.Id.Unknown = false
		data.Id.Null = true
	}
	if data.Hostname.Unknown {
		data.Hostname.Unknown = false
		data.Hostname.Null = true
	}
	if data.IpRouting.Unknown {
		data.IpRouting.Unknown = false
		data.IpRouting.Null = true
	}
	if data.Ipv6UnicastRouting.Unknown {
		data.Ipv6UnicastRouting.Unknown = false
		data.Ipv6UnicastRouting.Null = true
	}
	if data.Mtu.Unknown {
		data.Mtu.Unknown = false
		data.Mtu.Null = true
	}
	if data.IpSourceRoute.Unknown {
		data.IpSourceRoute.Unknown = false
		data.IpSourceRoute.Null = true
	}
	if data.IpDomainLookup.Unknown {
		data.IpDomainLookup.Unknown = false
		data.IpDomainLookup.Null = true
	}
	if data.IpDomainName.Unknown {
		data.IpDomainName.Unknown = false
		data.IpDomainName.Null = true
	}
	if data.LoginDelay.Unknown {
		data.LoginDelay.Unknown = false
		data.LoginDelay.Null = true
	}
	if data.LoginOnFailure.Unknown {
		data.LoginOnFailure.Unknown = false
		data.LoginOnFailure.Null = true
	}
	if data.LoginOnFailureLog.Unknown {
		data.LoginOnFailureLog.Unknown = false
		data.LoginOnFailureLog.Null = true
	}
	if data.LoginOnSuccess.Unknown {
		data.LoginOnSuccess.Unknown = false
		data.LoginOnSuccess.Null = true
	}
	if data.LoginOnSuccessLog.Unknown {
		data.LoginOnSuccessLog.Unknown = false
		data.LoginOnSuccessLog.Null = true
	}
	if data.MulticastRouting.Unknown {
		data.MulticastRouting.Unknown = false
		data.MulticastRouting.Null = true
	}
	if data.MulticastRoutingSwitch.Unknown {
		data.MulticastRoutingSwitch.Unknown = false
		data.MulticastRoutingSwitch.Null = true
	}
	if data.MulticastRoutingDistributed.Unknown {
		data.MulticastRoutingDistributed.Unknown = false
		data.MulticastRoutingDistributed.Null = true
	}
	for i := range data.MulticastRoutingVrfs {
		if data.MulticastRoutingVrfs[i].Vrf.Unknown {
			data.MulticastRoutingVrfs[i].Vrf.Unknown = false
			data.MulticastRoutingVrfs[i].Vrf.Null = true
		}
		if data.MulticastRoutingVrfs[i].Distributed.Unknown {
			data.MulticastRoutingVrfs[i].Distributed.Unknown = false
			data.MulticastRoutingVrfs[i].Distributed.Null = true
		}
	}
}

func (data *System) getDeletedListItems(ctx context.Context, state System) []string {
	deletedListItems := make([]string, 0)
	for i := range state.MulticastRoutingVrfs {
		stateKeyValues := [...]string{state.MulticastRoutingVrfs[i].Vrf.Value}

		emptyKeys := true
		if !reflect.ValueOf(state.MulticastRoutingVrfs[i].Vrf.Value).IsZero() {
			emptyKeys = false
		}
		if emptyKeys {
			continue
		}

		found := false
		for j := range data.MulticastRoutingVrfs {
			found = true
			if state.MulticastRoutingVrfs[i].Vrf.Value != data.MulticastRoutingVrfs[j].Vrf.Value {
				found = false
			}
			if found {
				break
			}
		}
		if !found {
			deletedListItems = append(deletedListItems, fmt.Sprintf("%v/ip/Cisco-IOS-XE-multicast:multicast-routing/vrf=%v", state.getPath(), strings.Join(stateKeyValues[:], ",")))
		}
	}
	return deletedListItems
}

func (data *System) getEmptyLeafsDelete(ctx context.Context) []string {
	emptyLeafsDelete := make([]string, 0)
	if !data.Ipv6UnicastRouting.Value {
		emptyLeafsDelete = append(emptyLeafsDelete, fmt.Sprintf("%v/ipv6/unicast-routing", data.getPath()))
	}
	if !data.MulticastRoutingSwitch.Value {
		emptyLeafsDelete = append(emptyLeafsDelete, fmt.Sprintf("%v/ip/Cisco-IOS-XE-multicast:mcr-conf/multicast-routing", data.getPath()))
	}
	if !data.MulticastRoutingDistributed.Value {
		emptyLeafsDelete = append(emptyLeafsDelete, fmt.Sprintf("%v/ip/Cisco-IOS-XE-multicast:multicast-routing/distributed", data.getPath()))
	}

	for i := range data.MulticastRoutingVrfs {
		keyValues := [...]string{data.MulticastRoutingVrfs[i].Vrf.Value}
		if !data.MulticastRoutingVrfs[i].Distributed.Value {
			emptyLeafsDelete = append(emptyLeafsDelete, fmt.Sprintf("%v/ip/Cisco-IOS-XE-multicast:multicast-routing/vrf=%v/distributed", data.getPath(), strings.Join(keyValues[:], ",")))
		}
	}
	return emptyLeafsDelete
}
