// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"fmt"
	"reflect"
	"regexp"
	"strconv"

	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/netascode/terraform-provider-iosxe/internal/provider/helpers"
	"github.com/tidwall/gjson"
	"github.com/tidwall/sjson"
)

type System struct {
	Device                      types.String                 `tfsdk:"device"`
	Id                          types.String                 `tfsdk:"id"`
	Hostname                    types.String                 `tfsdk:"hostname"`
	IpRouting                   types.Bool                   `tfsdk:"ip_routing"`
	Ipv6UnicastRouting          types.Bool                   `tfsdk:"ipv6_unicast_routing"`
	Mtu                         types.Int64                  `tfsdk:"mtu"`
	MulticastRouting            types.Bool                   `tfsdk:"multicast_routing"`
	MulticastRoutingSwitch      types.Bool                   `tfsdk:"multicast_routing_switch"`
	MulticastRoutingDistributed types.Bool                   `tfsdk:"multicast_routing_distributed"`
	MulticastRoutingVrfs        []SystemMulticastRoutingVrfs `tfsdk:"multicast_routing_vrfs"`
}
type SystemMulticastRoutingVrfs struct {
	Vrf         types.String `tfsdk:"vrf"`
	Distributed types.Bool   `tfsdk:"distributed"`
}

func (data System) getPath() string {
	return "Cisco-IOS-XE-native:native"
}

// if last path element has a key -> remove it
func (data System) getPathShort() string {
	path := data.getPath()
	re := regexp.MustCompile(`(.*)=[^\/]*$`)
	matches := re.FindStringSubmatch(path)
	if len(matches) <= 1 {
		return path
	}
	return matches[1]
}

func (data System) toBody() string {
	body := `{"` + helpers.LastElement(data.getPath()) + `":{}}`
	if !data.Hostname.Null && !data.Hostname.Unknown {
		body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"hostname", data.Hostname.Value)
	}
	if !data.IpRouting.Null && !data.IpRouting.Unknown {
		body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"ip.routing-conf.routing", data.IpRouting.Value)
	}
	if !data.Ipv6UnicastRouting.Null && !data.Ipv6UnicastRouting.Unknown {
		if data.Ipv6UnicastRouting.Value {
			body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"ipv6.unicast-routing", map[string]string{})
		}
	}
	if !data.Mtu.Null && !data.Mtu.Unknown {
		body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"system.Cisco-IOS-XE-switch:mtu.size", strconv.FormatInt(data.Mtu.Value, 10))
	}
	if !data.MulticastRouting.Null && !data.MulticastRouting.Unknown {
		if data.MulticastRouting.Value {
			body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"ip.Cisco-IOS-XE-multicast:multicast-routing", map[string]string{})
		}
	}
	if !data.MulticastRoutingSwitch.Null && !data.MulticastRoutingSwitch.Unknown {
		if data.MulticastRoutingSwitch.Value {
			body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"ip.Cisco-IOS-XE-multicast:mcr-conf.multicast-routing", map[string]string{})
		}
	}
	if !data.MulticastRoutingDistributed.Null && !data.MulticastRoutingDistributed.Unknown {
		if data.MulticastRoutingDistributed.Value {
			body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"ip.Cisco-IOS-XE-multicast:multicast-routing.distributed", map[string]string{})
		}
	}
	if len(data.MulticastRoutingVrfs) > 0 {
		body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"ip.Cisco-IOS-XE-multicast:multicast-routing.vrf", []interface{}{})
		for index, item := range data.MulticastRoutingVrfs {
			if !item.Vrf.Null && !item.Vrf.Unknown {
				body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"ip.Cisco-IOS-XE-multicast:multicast-routing.vrf"+"."+strconv.Itoa(index)+"."+"name", item.Vrf.Value)
			}
			if !item.Distributed.Null && !item.Distributed.Unknown {
				if item.Distributed.Value {
					body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"ip.Cisco-IOS-XE-multicast:multicast-routing.vrf"+"."+strconv.Itoa(index)+"."+"distributed", map[string]string{})
				}
			}
		}
	}
	return body
}

func (data *System) updateFromBody(res gjson.Result) {
	prefix := helpers.LastElement(data.getPath()) + "."
	if res.Get(helpers.LastElement(data.getPath())).IsArray() {
		prefix += "0."
	}
	if value := res.Get(prefix + "hostname"); value.Exists() {
		data.Hostname.Value = value.String()
	} else {
		data.Hostname.Null = true
	}
	if value := res.Get(prefix + "ip.routing-conf.routing"); value.Exists() {
		data.IpRouting.Value = value.Bool()
	} else {
		data.IpRouting.Value = false
	}
	if value := res.Get(prefix + "ipv6.unicast-routing"); value.Exists() {
		data.Ipv6UnicastRouting.Value = true
	} else {
		data.Ipv6UnicastRouting.Value = false
	}
	if value := res.Get(prefix + "system.Cisco-IOS-XE-switch:mtu.size"); value.Exists() {
		data.Mtu.Value = value.Int()
	} else {
		data.Mtu.Null = true
	}
	if value := res.Get(prefix + "ip.Cisco-IOS-XE-multicast:multicast-routing"); value.Exists() {
		data.MulticastRouting.Value = true
	} else {
		data.MulticastRouting.Value = false
	}
	if value := res.Get(prefix + "ip.Cisco-IOS-XE-multicast:mcr-conf.multicast-routing"); value.Exists() {
		data.MulticastRoutingSwitch.Value = true
	} else {
		data.MulticastRoutingSwitch.Value = false
	}
	if value := res.Get(prefix + "ip.Cisco-IOS-XE-multicast:multicast-routing.distributed"); value.Exists() {
		data.MulticastRoutingDistributed.Value = true
	} else {
		data.MulticastRoutingDistributed.Value = false
	}
	for i := range data.MulticastRoutingVrfs {
		key := data.MulticastRoutingVrfs[i].Vrf.Value
		if value := res.Get(fmt.Sprintf("%vip.Cisco-IOS-XE-multicast:multicast-routing.vrf.#(name==\"%v\").name", prefix, key)); value.Exists() {
			data.MulticastRoutingVrfs[i].Vrf.Value = value.String()
		} else {
			data.MulticastRoutingVrfs[i].Vrf.Null = true
		}
		if value := res.Get(fmt.Sprintf("%vip.Cisco-IOS-XE-multicast:multicast-routing.vrf.#(name==\"%v\").distributed", prefix, key)); value.Exists() {
			data.MulticastRoutingVrfs[i].Distributed.Value = true
		} else {
			data.MulticastRoutingVrfs[i].Distributed.Value = false
		}
	}
}

func (data *System) fromBody(res gjson.Result) {
	prefix := helpers.LastElement(data.getPath()) + "."
	if res.Get(helpers.LastElement(data.getPath())).IsArray() {
		prefix += "0."
	}
	if value := res.Get(prefix + "hostname"); value.Exists() {
		data.Hostname.Value = value.String()
		data.Hostname.Null = false
	}
	if value := res.Get(prefix + "ip.routing-conf.routing"); value.Exists() {
		data.IpRouting.Value = value.Bool()
		data.IpRouting.Null = false
	} else {
		data.IpRouting.Value = false
		data.IpRouting.Null = false
	}
	if value := res.Get(prefix + "ipv6.unicast-routing"); value.Exists() {
		data.Ipv6UnicastRouting.Value = true
		data.Ipv6UnicastRouting.Null = false
	} else {
		data.Ipv6UnicastRouting.Value = false
		data.Ipv6UnicastRouting.Null = false
	}
	if value := res.Get(prefix + "system.Cisco-IOS-XE-switch:mtu.size"); value.Exists() {
		data.Mtu.Value = value.Int()
		data.Mtu.Null = false
	}
	if value := res.Get(prefix + "ip.Cisco-IOS-XE-multicast:multicast-routing"); value.Exists() {
		data.MulticastRouting.Value = true
		data.MulticastRouting.Null = false
	} else {
		data.MulticastRouting.Value = false
		data.MulticastRouting.Null = false
	}
	if value := res.Get(prefix + "ip.Cisco-IOS-XE-multicast:mcr-conf.multicast-routing"); value.Exists() {
		data.MulticastRoutingSwitch.Value = true
		data.MulticastRoutingSwitch.Null = false
	} else {
		data.MulticastRoutingSwitch.Value = false
		data.MulticastRoutingSwitch.Null = false
	}
	if value := res.Get(prefix + "ip.Cisco-IOS-XE-multicast:multicast-routing.distributed"); value.Exists() {
		data.MulticastRoutingDistributed.Value = true
		data.MulticastRoutingDistributed.Null = false
	} else {
		data.MulticastRoutingDistributed.Value = false
		data.MulticastRoutingDistributed.Null = false
	}
	if value := res.Get(prefix + "ip.Cisco-IOS-XE-multicast:multicast-routing.vrf"); value.Exists() {
		data.MulticastRoutingVrfs = make([]SystemMulticastRoutingVrfs, 0)
		value.ForEach(func(k, v gjson.Result) bool {
			item := SystemMulticastRoutingVrfs{}
			if cValue := v.Get("name"); cValue.Exists() {
				item.Vrf.Value = cValue.String()
				item.Vrf.Null = false
			}
			if cValue := v.Get("distributed"); cValue.Exists() {
				item.Distributed.Value = true
				item.Distributed.Null = false
			}
			data.MulticastRoutingVrfs = append(data.MulticastRoutingVrfs, item)
			return true
		})
	}
}

func (data *System) setUnknownValues() {
	if data.Device.Unknown {
		data.Device.Unknown = false
		data.Device.Null = true
	}
	if data.Id.Unknown {
		data.Id.Unknown = false
		data.Id.Null = true
	}
	if data.Hostname.Unknown {
		data.Hostname.Unknown = false
		data.Hostname.Null = true
	}
	if data.IpRouting.Unknown {
		data.IpRouting.Unknown = false
		data.IpRouting.Null = true
	}
	if data.Ipv6UnicastRouting.Unknown {
		data.Ipv6UnicastRouting.Unknown = false
		data.Ipv6UnicastRouting.Null = true
	}
	if data.Mtu.Unknown {
		data.Mtu.Unknown = false
		data.Mtu.Null = true
	}
	if data.MulticastRouting.Unknown {
		data.MulticastRouting.Unknown = false
		data.MulticastRouting.Null = true
	}
	if data.MulticastRoutingSwitch.Unknown {
		data.MulticastRoutingSwitch.Unknown = false
		data.MulticastRoutingSwitch.Null = true
	}
	if data.MulticastRoutingDistributed.Unknown {
		data.MulticastRoutingDistributed.Unknown = false
		data.MulticastRoutingDistributed.Null = true
	}
	for i := range data.MulticastRoutingVrfs {
		if data.MulticastRoutingVrfs[i].Vrf.Unknown {
			data.MulticastRoutingVrfs[i].Vrf.Unknown = false
			data.MulticastRoutingVrfs[i].Vrf.Null = true
		}
		if data.MulticastRoutingVrfs[i].Distributed.Unknown {
			data.MulticastRoutingVrfs[i].Distributed.Unknown = false
			data.MulticastRoutingVrfs[i].Distributed.Null = true
		}
	}
}

func (data *System) getDeletedListItems(state System) []string {
	deletedListItems := make([]string, 0)
	for _, i := range state.MulticastRoutingVrfs {
		if reflect.ValueOf(i.Vrf.Value).IsZero() {
			continue
		}
		found := false
		for _, j := range data.MulticastRoutingVrfs {
			if i.Vrf.Value == j.Vrf.Value {
				found = true
			}
		}
		if !found {
			deletedListItems = append(deletedListItems, fmt.Sprintf("%v/ip/Cisco-IOS-XE-multicast:multicast-routing/vrf=%v", state.getPath(), i.Vrf.Value))
		}
	}
	return deletedListItems
}

func (data *System) getEmptyLeafsDelete() []string {
	emptyLeafsDelete := make([]string, 0)
	if !data.Ipv6UnicastRouting.Value {
		emptyLeafsDelete = append(emptyLeafsDelete, fmt.Sprintf("%v/ipv6/unicast-routing", data.getPath()))
	}
	if !data.MulticastRoutingSwitch.Value {
		emptyLeafsDelete = append(emptyLeafsDelete, fmt.Sprintf("%v/ip/Cisco-IOS-XE-multicast:mcr-conf/multicast-routing", data.getPath()))
	}
	if !data.MulticastRoutingDistributed.Value {
		emptyLeafsDelete = append(emptyLeafsDelete, fmt.Sprintf("%v/ip/Cisco-IOS-XE-multicast:multicast-routing/distributed", data.getPath()))
	}
	return emptyLeafsDelete
}
