// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestAccIosxeMSDPVRF(t *testing.T) {
	var checks []resource.TestCheckFunc
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_msdp_vrf.test", "vrf", "VRF1"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_msdp_vrf.test", "originator_id", "Loopback100"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_msdp_vrf.test", "passwords.0.addr", "10.1.1.1"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_msdp_vrf.test", "passwords.0.encryption", "0"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_msdp_vrf.test", "passwords.0.password", "Cisco123"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_msdp_vrf.test", "peers.0.addr", "10.1.1.1"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_msdp_vrf.test", "peers.0.remote_as", "65000"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_msdp_vrf.test", "peers.0.connect_source_loopback", "100"))
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccIosxeMSDPVRFPrerequisitesConfig + testAccIosxeMSDPVRFConfig_all(),
				Check:  resource.ComposeTestCheckFunc(checks...),
			},
			{
				ResourceName:  "iosxe_msdp_vrf.test",
				ImportState:   true,
				ImportStateId: "Cisco-IOS-XE-native:native/ip/Cisco-IOS-XE-multicast:msdp/vrf=VRF1",
			},
		},
	})
}

const testAccIosxeMSDPVRFPrerequisitesConfig = `
resource "iosxe_restconf" "PreReq0" {
	path = "Cisco-IOS-XE-native:native/vrf/definition=VRF1"
	delete = false
	attributes = {
		"name" = "VRF1"
		"address-family/ipv4" = ""
	}
}

resource "iosxe_restconf" "PreReq1" {
	path = "Cisco-IOS-XE-native:native/interface/Loopback=100"
	attributes = {
		"name" = "100"
		"vrf/forwarding" = "VRF1"
	}
	depends_on = [iosxe_restconf.PreReq0, ]
}

`

func testAccIosxeMSDPVRFConfig_minimum() string {
	config := `resource "iosxe_msdp_vrf" "test" {` + "\n"
	config += `	vrf = "VRF1"` + "\n"
	config += `	depends_on = [iosxe_restconf.PreReq0, iosxe_restconf.PreReq1, ]` + "\n"
	config += `}` + "\n"
	return config
}

func testAccIosxeMSDPVRFConfig_all() string {
	config := `resource "iosxe_msdp_vrf" "test" {` + "\n"
	config += `	vrf = "VRF1"` + "\n"
	config += `	originator_id = "Loopback100"` + "\n"
	config += `	passwords = [{` + "\n"
	config += `		addr = "10.1.1.1"` + "\n"
	config += `		encryption = 0` + "\n"
	config += `		password = "Cisco123"` + "\n"
	config += `	}]` + "\n"
	config += `	peers = [{` + "\n"
	config += `		addr = "10.1.1.1"` + "\n"
	config += `		remote_as = 65000` + "\n"
	config += `		connect_source_loopback = 100` + "\n"
	config += `	}]` + "\n"
	config += `	depends_on = [iosxe_restconf.PreReq0, iosxe_restconf.PreReq1, ]` + "\n"
	config += `}` + "\n"
	return config
}
