// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestAccIosxeUsername(t *testing.T) {
	var checks []resource.TestCheckFunc
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_username.test", "name", "user1"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_username.test", "privilege", "15"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_username.test", "description", "User1 description"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_username.test", "password_encryption", "0"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_username.test", "password", "MyPassword"))
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccIosxeUsernameConfig_all(),
				Check:  resource.ComposeTestCheckFunc(checks...),
			},
			{
				ResourceName:  "iosxe_username.test",
				ImportState:   true,
				ImportStateId: "Cisco-IOS-XE-native:native/username=user1",
			},
		},
	})
}

func testAccIosxeUsernameConfig_minimum() string {
	config := `resource "iosxe_username" "test" {` + "\n"
	config += `	name = "user1"` + "\n"
	config += `}` + "\n"
	return config
}

func testAccIosxeUsernameConfig_all() string {
	config := `resource "iosxe_username" "test" {` + "\n"
	config += `	name = "user1"` + "\n"
	config += `	privilege = 15` + "\n"
	config += `	description = "User1 description"` + "\n"
	config += `	password_encryption = "0"` + "\n"
	config += `	password = "MyPassword"` + "\n"
	config += `}` + "\n"
	return config
}
