// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestAccIosxeLoggingIPv6HostVRFTransport(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccIosxeLoggingIPv6HostVRFTransportPrerequisitesConfig + testAccIosxeLoggingIPv6HostVRFTransportConfig_all(),
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr("iosxe_logging_ipv6_host_vrf_transport.test", "ipv6_host", "2001::1"),
					resource.TestCheckResourceAttr("iosxe_logging_ipv6_host_vrf_transport.test", "vrf", "VRF1"),
					resource.TestCheckResourceAttr("iosxe_logging_ipv6_host_vrf_transport.test", "transport_udp_ports.0.port_number", "10000"),
					resource.TestCheckResourceAttr("iosxe_logging_ipv6_host_vrf_transport.test", "transport_tcp_ports.0.port_number", "10001"),
					resource.TestCheckResourceAttr("iosxe_logging_ipv6_host_vrf_transport.test", "transport_tls_ports.0.port_number", "10002"),
				),
			},
			{
				ResourceName:  "iosxe_logging_ipv6_host_vrf_transport.test",
				ImportState:   true,
				ImportStateId: "Cisco-IOS-XE-native:native/logging/host/ipv6/ipv6-host-vrf-transport-list=2001::1,VRF1",
			},
		},
	})
}

const testAccIosxeLoggingIPv6HostVRFTransportPrerequisitesConfig = `
resource "iosxe_restconf" "PreReq0" {
	path = "Cisco-IOS-XE-native:native/vrf/definition=VRF1"
	delete = false
	attributes = {
		"name" = "VRF1"
		"address-family/ipv4" = ""
		"address-family/ipv6" = ""
	}
}

`

func testAccIosxeLoggingIPv6HostVRFTransportConfig_minimum() string {
	return `
	resource "iosxe_logging_ipv6_host_vrf_transport" "test" {
		ipv6_host = "2001::1"
		vrf = "VRF1"
		depends_on = [iosxe_restconf.PreReq0, ]
	}
	`
}

func testAccIosxeLoggingIPv6HostVRFTransportConfig_all() string {
	return `
	resource "iosxe_logging_ipv6_host_vrf_transport" "test" {
		ipv6_host = "2001::1"
		vrf = "VRF1"
		transport_udp_ports = [{
			port_number = 10000
		}]
		transport_tcp_ports = [{
			port_number = 10001
		}]
		transport_tls_ports = [{
			port_number = 10002
		}]
		depends_on = [iosxe_restconf.PreReq0, ]
	}
	`
}
