// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestAccIosxeBanner(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccIosxeBannerConfig_all(),
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr("iosxe_banner.test", "exec_banner", "My Exec Banner"),
					resource.TestCheckResourceAttr("iosxe_banner.test", "login_banner", "My Login Banner"),
					resource.TestCheckResourceAttr("iosxe_banner.test", "prompt_timeout_banner", "My Prompt-Timeout Banner"),
					resource.TestCheckResourceAttr("iosxe_banner.test", "motd_banner", "My MOTD Banner"),
				),
			},
			{
				ResourceName:  "iosxe_banner.test",
				ImportState:   true,
				ImportStateId: "Cisco-IOS-XE-native:native/banner",
			},
		},
	})
}

func testAccIosxeBannerConfig_minimum() string {
	return `
	resource "iosxe_banner" "test" {
	}
	`
}

func testAccIosxeBannerConfig_all() string {
	return `
	resource "iosxe_banner" "test" {
		exec_banner = "My Exec Banner"
		login_banner = "My Login Banner"
		prompt_timeout_banner = "My Prompt-Timeout Banner"
		motd_banner = "My MOTD Banner"
	}
	`
}
