// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestAccIosxeMDTSubscription(t *testing.T) {
	var checks []resource.TestCheckFunc
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_mdt_subscription.test", "subscription_id", "101"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_mdt_subscription.test", "stream", "yang-notif-native"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_mdt_subscription.test", "encoding", "encode-kvgpb"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_mdt_subscription.test", "source_vrf", "Mgmt-vrf"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_mdt_subscription.test", "source_address", "1.2.3.4"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_mdt_subscription.test", "update_policy_on_change", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_mdt_subscription.test", "filter_xpath", "/ios-events-ios-xe-oper:ospf-neighbor-state-change"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_mdt_subscription.test", "receivers.0.address", "5.6.7.8"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_mdt_subscription.test", "receivers.0.port", "57600"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_mdt_subscription.test", "receivers.0.protocol", "grpc-tcp"))
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccIosxeMDTSubscriptionConfig_all(),
				Check:  resource.ComposeTestCheckFunc(checks...),
			},
			{
				ResourceName:  "iosxe_mdt_subscription.test",
				ImportState:   true,
				ImportStateId: "Cisco-IOS-XE-mdt-cfg:mdt-config-data/mdt-subscription=101",
			},
		},
	})
}

func testAccIosxeMDTSubscriptionConfig_minimum() string {
	config := `resource "iosxe_mdt_subscription" "test" {` + "\n"
	config += `	subscription_id = 101` + "\n"
	config += `}` + "\n"
	return config
}

func testAccIosxeMDTSubscriptionConfig_all() string {
	config := `resource "iosxe_mdt_subscription" "test" {` + "\n"
	config += `	subscription_id = 101` + "\n"
	config += `	stream = "yang-notif-native"` + "\n"
	config += `	encoding = "encode-kvgpb"` + "\n"
	config += `	source_vrf = "Mgmt-vrf"` + "\n"
	config += `	source_address = "1.2.3.4"` + "\n"
	config += `	update_policy_on_change = true` + "\n"
	config += `	filter_xpath = "/ios-events-ios-xe-oper:ospf-neighbor-state-change"` + "\n"
	config += `	receivers = [{` + "\n"
	config += `		address = "5.6.7.8"` + "\n"
	config += `		port = 57600` + "\n"
	config += `		protocol = "grpc-tcp"` + "\n"
	config += `	}]` + "\n"
	config += `}` + "\n"
	return config
}
